import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
// import styles from "../styles/Home.module.css";
import styles from "@/styles/Home.module.css";
import { person } from "../data";
import dynamic from 'next/dynamic';
import { useState } from 'react';

const HelloComponent = dynamic(() => import ('../components/hello'), {
	loading: () => <b>Loading ...</b>
});

export default function Home() {

	const [showHello, SetShowHello] = useState(false);

  	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to Training Next.js!
				</h1>

				<h2>
					<Link href={{pathname: "/heroes", query: {title: 'Heroes List'}}} as={'/heroes'}>
						<a>List Heroes</a>
					</Link>
				</h2>

				{ showHello ? <HelloComponent /> : null }
				<button onClick={() => SetShowHello(!showHello)}>
					Click me!
				</button>

				{/* <h2>Heroes Name</h2>
				<ul>
					{ person.map((persons) =>
						<li>
							<Link href={{pathname: `/personal/${persons.allies}`, 
								query:{ 
									name: persons.name, 
									gender: persons.gender, 
									position: persons.position, 
									profession: persons.profession }}} 
								as ={`/personal/${persons.allies}`}>
								<a>{ persons.name }</a>
							</Link>
						</li>
					)}
				</ul> */}
			</main>
		</div>
	);
}
